### ISSUE TITLE
[Review] Requirements V0.2

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/docs#1]
Cloud-Barista 커뮤니티 멤버들 께서는 
요구사항정의서 V0.2 문서를 검토 해주시기 바랍니다. 

====== V0.2 작성 기준 ====
  * 요구사항 버전: V0.2 
  * 요구사항 대상: 멀티 클라우드 서비스 공통 프레임워크 1단계 결과물(1단계: 1-2차년도)
  * 사용자요구사항: 사용자 관점에서  시스템 밖에서 필요한 개략적인 요구 기능 
  * 시스템요구사항: 시스템 안에서 사용자 요구사항을 만족시키기 위한 시스템 수준의 요구 기능

====== V0.2 작성 기준 ====

**<검토 의견 형식>**
  * 7page 6line: '최적의 컴퓨 인프라를' => '최적의 컴퓨팅 인프라를'로 수정.
  * 7page 그림1: 좌측 상단의 xxx 의미가 'yyyy'인지 검토 요함.

**<검토 의견 제출 방법>**
 * 현 이슈에 Comment로 추가

**Comment by kyongminkwon** [comment]
4page 8line : '당사자 간의 시스템의 개발 범위에' => '당사자 간의 시스템 개발 범위에'  (문구정리)
4page 20line : '사용자 요구사항 및 시스템 요구사항' => '사용자 및 시스템 요구사항' (중복 문구)
7page 6line : '개발 중에 있다.' => '개발 중이다.' (추천)
15page 1line : '제공 해야 한다.' => '제공해야 한다.' (띄어쓰기 오류)
15page 1line : '이종의 멀티 클라우드 인프라를' => '이종의 클라우드 인프라들을' (추천)
15page 5line : '변경 가능한 구조를 제공 해야한다.' => '변경할 수 있어야 한다.' (기능 컨셉으로 작성 추천)
16page 1line : '확장 가능한 모니터링 프레임워크 구조를 제공해야 한다.' => '확장 기능을 제공해야 한다.' (기능 컨셉으로 작성 추천)
16page 1line : '통합 모니터링 프레임워크 구조를 제공해야 한다.' => '통합 모니터링 기능을 제공해야 한다.' (기능 컨셉으로 작성 추천)

**Comment by zephy-mzc** [comment]
* 과제용 문서인지 오픈소스 프로젝트 문서인지 구분할 필요가 있어보입니다.
    4page 4line : "과제" ==> "오픈소스 프로젝트" 
    4page 11line, : "과제" ==> "오픈소스 프로젝트"
    10page 2line: "과제" ==> "오픈소스 프로젝트"

11page "사용 시나리오" 추가하면 어떨지 생각해 보았습니다. : 

사용자는 이용하고자 하는 클라우드 드라어버를 확장 Plugin 한다.
    - Plugin에 따른 클라우드 Identity 정보를 등록한다.
    - 확장에 따른 대상 클라우드가 추가된다.

사용자는 이용하고자 하는 클라우드를 연동한다.
    - 클라우드 연결을 위해 Key 정보 등 설정한다.
    - 클라우드 연결이 완성되면 클라우드 객체 정보(이미지 등)의 동기화를 진행한다.

사용자는 WEB/WAS 서비스를 위한 생성을 지원한다.
    - default VPC 및 네트워크 정의 (VPC는 AWS 객체 용어 이지만 임의로 이용함)
    - default 보안 정의
    - 지정 서버 이미지를 통해 서비스용 서버를 생성한다.
        - 동기화된 이미지를 선택한다.
        - 디스크를 생성하고 선택한다.
      * (Optional) LoadBalancer를 구성한다.
      * (Optional) Auto Scale 구성을 지원한다.

사용자는 생성된 서버에 접속하여 Web/WAS를 구성한다.
        - 생성된 서버 접근 방법을 제공한다. (ID/Password, Secret Ket, ...)
        - DevOps를 활용하여 Web/Was 서비스를 구성한다. (ProtoType)

사용자는 구성된 Web/Was 를 확인하고 실행중인 서버를 중지 > 시작 > 종료한다.
        - 서비스 Url을 접속하여 Browser에서 확인한다.
        - 실행중인 서버를 중지한다.
        - 중지된 서버를 실행한다.
        - 실행중인 서버를 중지하고 종료한다.

(Optional) 멀티클라우드 시나리오 추가
        - 제공중인 Web/Was 서비스를 이종 클라우드로 이관한다.
        - 이관된 클라우드에서 서비스 제공을 확인한다.

**Comment by powerkimhub** [comment]
@kyongminkwon 검토 의견 감사드립니다. 
검토의견 반영 내용이 다음과 같으며, 요구사항 정의서 V0.3에 반영 예정입니다.

> 4page 8line : '당사자 간의 시스템의 개발 범위에' => '당사자 간의 시스템 개발 범위에' (문구정리)
   => 반영
> 4page 20line : '사용자 요구사항 및 시스템 요구사항' => '사용자 및 시스템 요구사항' (중복 문구)
  => 반영
> 7page 6line : '개발 중에 있다.' => '개발 중이다.' (추천)
  => 반영
> 15page 1line : '제공 해야 한다.' => '제공해야 한다.' (띄어쓰기 오류)
  => 반영
> 15page 1line : '이종의 멀티 클라우드 인프라를' => '이종의 클라우드 인프라들을' (추천)
  => 반영
> 15page 5line : '변경 가능한 구조를 제공 해야한다.' => '변경할 수 있어야 한다.' (기능 컨셉으로 작성 추천)
  => 미반영 사유: 상기 이슈 내 작성 기준에서 시스템 요구 사항을 아래와 같이 정의함.
        * 시스템요구사항: 시스템 안에서 사용자 요구사항을 만족시키기 위한 시스템 수준의 요구 기능 
> 16page 1line : '확장 가능한 모니터링 프레임워크 구조를 제공해야 한다.' => '확장 기능을 제공해야 한다.' (기능 컨셉으로 작성 추천)
  => 미반영 사유: 상기 이슈 내 작성 기준에서 시스템 요구 사항을 아래와 같이 정의함.
        * 시스템요구사항: 시스템 안에서 사용자 요구사항을 만족시키기 위한 시스템 수준의 요구 기능 
> 16page 1line : '통합 모니터링 프레임워크 구조를 제공해야 한다.' => '통합 모니터링 기능을 제공해야 한다.' (기능 컨셉으로 작성 추천)
  => 미반영 사유: 상기 이슈 내 작성 기준에서 시스템 요구 사항을 아래와 같이 정의함.
        * 시스템요구사항: 시스템 안에서 사용자 요구사항을 만족시키기 위한 시스템 수준의 요구 기능

**Comment by powerkimhub** [comment]
@zephy-mzc 검토 의견 감사드립니다.
검토의견 반영 내용이 다음과 같으며, 요구사항 정의서 V0.3에 반영 예정입니다.

> * 과제용 문서인지 오픈소스 프로젝트 문서인지 구분할 필요가 있어보입니다.
    >   4page 4line : "과제" ==> "오픈소스 프로젝트"
    >   4page 11line, : "과제" ==> "오픈소스 프로젝트"
    >   10page 2line: "과제" ==> "오픈소스 프로젝트"
  => 정부 과제에 근간(펀드)을 둔 공개SW 프로젝트이어서 유지 의무(과제 진행 및 결과물을 공개)
 
> 11page "사용 시나리오" 추가하면 어떨지 생각해 보았습니다. :
> 
> 사용자는 이용하고자 하는 클라우드 드라어버를 확장 Plugin 한다.
> - Plugin에 따른 클라우드 Identity 정보를 등록한다.
> - 확장에 따른 대상 클라우드가 추가된다.
> 
> 사용자는 이용하고자 하는 클라우드를 연동한다.
> - 클라우드 연결을 위해 Key 정보 등 설정한다.
> - 클라우드 연결이 완성되면 클라우드 객체 정보(이미지 등)의 동기화를 진행한다.
> 
> 사용자는 WEB/WAS 서비스를 위한 생성을 지원한다.
> - default VPC 및 네트워크 정의 (VPC는 AWS 객체 용어 이지만 임의로 이용함)
> - default 보안 정의
> - 지정 서버 이미지를 통해 서비스용 서버를 생성한다.
> - 동기화된 이미지를 선택한다.
> - 디스크를 생성하고 선택한다.
> * (Optional) LoadBalancer를 구성한다.
> * (Optional) Auto Scale 구성을 지원한다.
> 
> 사용자는 생성된 서버에 접속하여 Web/WAS를 구성한다.
> - 생성된 서버 접근 방법을 제공한다. (ID/Password, Secret Ket, ...)
> - DevOps를 활용하여 Web/Was 서비스를 구성한다. (ProtoType)
> 
> 사용자는 구성된 Web/Was 를 확인하고 실행중인 서버를 중지 > 시작 > 종료한다.
> - 서비스 Url을 접속하여 Browser에서 확인한다.
> - 실행중인 서버를 중지한다.
> - 중지된 서버를 실행한다.
> - 실행중인 서버를 중지하고 종료한다.
> 
> (Optional) 멀티클라우드 시나리오 추가
> - 제공중인 Web/Was 서비스를 이종 클라우드로 이관한다.
> - 이관된 클라우드에서 서비스 제공을 확인한다.
  => 좋은 제안 및 정보 감사드립니다. 향후 버전 작업시 고려토록 하겠습니다.

**Comment by powerkimhub** [comment]
커뮤니티 검토 의견 반영 및 요구사항 정의서 V0.3 공개
* [https://github.com/cloud-barista/docs/blob/master/requirements/(Cloud-Barista)Requirements(V0.3)-2019.06.18.pdf](url)
