### ISSUE TITLE
[Suggestion] Cb_User_Functions.md moved to the 'features' directory

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/docs#19]
- How about Cb_User_Functions.md going to 'features' directory?
- In my opinion, it's not about design.

#### [AS-IS]
- design/CB-User_Functions.md

#### [TO-BE]
-  ex) features/CB-User_Functions.md

**Comment by innodreamer** [comment]
- 제안해주신대로 CB-User_Functions.md 파일 위치를 변경했습니다.
   :  ./design/CB-User_Functions.md -> ./features/CB-User_Functions.md
