### ISSUE TITLE
[Suggestion] name and position of 'CB-User_gRPC-API.md'

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/docs#20]
The contents of 'CB-User_gRPC-API.md' is not pure API Spec.
It's near to design.

In my opinion. We have two choices.
#### (1) same dir & rename:
  - ex) API/CB-User_Go-API_design.md

#### (2) rename & moved to the 'design' dir :
  - ex) design/CB-User_Go-API_design.md

**Comment by innodreamer** [comment]
- 제안해주신대로 design 디렉토리 위치로 옮기고 파일명을 변경했습니다.
   => ./design/CB-User_gRPC-Go-API_design.md

관련하여, API 디렉토리의 update guide 문서 파일명도 아래와 같이 변경했습니다.
 => ./API/CB-User_gRPC-Go-API-update_guide.md
