### ISSUE TITLE
To delete the directory (cloud-barista/docs/design/)

### ISSUE THREAD

**Issue by innodreamer** [cloud-barista/docs#23]
cloud-barista/docs 바로 아래에 있는 '/design/' 디렉토리를 link를 위해 임시로 만들어놨었는데,
실제 디렉토리인 cloud-barista/docs/technical_docs/design/ 디렉토리와 자주 혼동이 되니 이제 삭제하면 어떨까합니다.

**Comment by powerkimhub** [comment]
@innodreamer 
이제 지워도 좋을 것 같습니다.

**Comment by innodreamer** [comment]
@powerkimhub 예. 그 link를 삭제했습니다.
