### ISSUE TITLE
Check and correct links due to document management directory changes

### ISSUE THREAD

**Issue by yunkon-kim** [cloud-barista/docs#82]
Depending on the organization's decision, there will be changes to the directory structure.

This will cause issues with referencing links within the organization.

Therefore, we try to check and correct the links in each repository and wiki.

Work will be carried out sequentially.

(As-Is)
```bash
technical_docs
    ├── API
    ├── design
    ├── features
    └── requirements
```

(To-Be)
```bash
technical_docs
    ├── cloud-barista  
    │    ├── API
    │    ├── design
    │    ├── features
    │    └── requirements
    └── cloud-migrator
         ├── API
         ├── design
         ├── features
         └── requirements
```

**Comment by yunkon-kim** [comment]
@powerkimhub 

Early 배포가 예정되어 있어, cb-spider repo 및 wiki를 우선 확인하였습니다. 

(Repo) `technical_docs` 관련 경로는 검색되지 않았습니다.

(Wiki) 아래 한 부분이 검색 되었습니다.

Wiki 이므로 바로 반영하겠습니다.
_Sidebar.md
```diff
-    * [How to add a new API to the gRPC Go API](https://github.com/cloud-barista/docs/blob/master/technical_docs/API/CB-User_gRPC-Go-API-update_guide.md)
+    * [How to add a new API to the gRPC Go API](https://github.com/cloud-barista/docs/blob/master/technical_docs/cloud-barista/API/CB-User_gRPC-Go-API-update_guide.md)
```

**Comment by yunkon-kim** [comment]
@seokho-son 

cb-tumblebug repo에서 `technical_docs` 관련 경로는 검색되지 않았습니다.

wiki clone시 invalid path 이슈가 발생하였습니다. Wiki 이기 때문에 이슈 해결 및 링크 수정 작업을 모두 직접 반영하도록 하겠습니다.

**Comment by seokho-son** [comment]
I guess this issue has been resolved. :)
let me close, feel free to reopen if neccessary.
